name: Class Design Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install detekt
        run: |
          wget -O detekt-cli https://github.com/detekt/detekt/releases/download/v1.18.0/detekt-cli-1.18.0-all.jar

      - name: Run detekt
        run: |
          java -jar detekt-cli --input $GITHUB_WORKSPACE/src/main/kotlin
